name: CICD

on:
  push:
    branches: [ main , login-aws-oidc]

env:
  
  AWS_REGION : "us-east-1"

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::955213590927:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
      
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t sumansarkar/nodejs-app-test .
      - name: Publish image to docker hub
        run: docker push sumansarkar/nodejs-app-test:latest
      
        
  deploy:
    needs: build
    runs-on: [self-hosted, linux]
    steps:
      - name: Pull image from docker hub
        run: docker pull sumansarkar/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container sumansarkar/nodejs-app
